class TeamFeedPageXPaths:

    GNB_SELECTOR = "div.fixed.bottom-0.w-full.z-50.max-w-\\[600px\\].border-t-\\[1px\\].bg-white.border-gray-200.p-3.h-16"
    TEAM_FEED_SELECTOR = "a[href='/teams/1']"
    TEAM_FEED_ICON_SELECTOR = "svg.fill-current"
    COMBOBOX_SELECTOR = "button[role='combobox']"
    PROFILE_EDIT_ICON_SELECTOR = "div.flex.items-center.justify-between.text-subbody > svg.cursor-pointer"
    PROFILE_EDIT_FINISH_BTN_SELECTOR = "button.cursor-pointer[type='submit']"
    PROFILE_EDIT_X_BTN_SELECTOR = "button.text-2xl.cursor-pointer"
    TEAM_EATEN_MENU_ADD_BTN_SELECTOR = "div.flex.items-center.gap-4 > button"
    NEW_REVIEW_FINISH_BTN_XPATH = "//button[text()='후기 작성 완료']"
    COMBOBOX_TEAM_XPATH = "//span[text()='개발 1팀']"
    TEAM_FEED_TITLE_XPATH = "//span[text()='팀 피드']"
    FOOD_TENDENCY_XPATH = "//span[contains(text(), '음식 성향')]"
    TEAM_STATS_XPATH = "//span[contains(text(), '팀 통계')]"
    TEAM_EATEN_MENU_XPATH = "//span[contains(text(), '팀이 먹은 메뉴')]"
    TEAM_NAME_SELECTOR = "div.px-2.py-1.rounded-lg.bg-sub-2 > span"
    TEAM_SWEET_FLAVOR_SELECTOR = "section:nth-child(2) > span.font-semibold.w-14.text-main-black"
    TEAM_SALTY_FLAVOR_SELECTOR = "section:nth-child(3) > span.font-semibold.w-14.text-main-black"
    TEAM_SPICY_FLAVOR_SELECTOR = "section:nth-child(4) > span.font-semibold.w-14.text-main-black"
    TEAM_FAVORITE_FOOD_XPATH = "//*[@id='root']/div[1]/main/section/section/section/div[2]/div[1]/p"
    TEAM_HATE_FOOD_XPATH = "//*[@id='root']/div[1]/main/section/section/section/div[2]/div[2]/p"
    PROFILE_EDIT_XPATH = "//span[text()='프로필 정보 수정']"
    SWEET_SLIDER_XPATH = "//section[contains(., '단 맛')]//span[@role='slider']"
    SOLO_DINNER_XPATH = "//div[@class='inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-main text-white' and text()='혼밥']"
    GROUP_DINNER_XPATH = "//div[@class='inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-main text-white' and text()='그룹']"
    TEAM_DINNER_XPATH = "//div[@class='inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-main text-white' and text()='회식']"
    REVIEW_CONTAINER_CSS = "div.flex.w-full.gap-6.p-4.shadow-md.rounded-2xl"
    ADD_REVIEW_TITLE_XPATH = "//span[text()='새로운 후기 등록하기']"
    MENU_REQUIRED_MESSAGE_XPATH = "//p[contains(text(), '메뉴명은 필수입니다')]"
    CATEGORY_REQUIRED_MESSAGE_XPATH = "//p[contains(text(), '카테고리는 필수입니다')]"
    REVIEW_REQUIRED_MESSAGE_XPATH = "//p[contains(text(), '후기는 필수입니다')]"
    STAR_REQUIRED_MESSAGE_XPATH = "//p[contains(text(), '별점은 최소 1점 이상이어야 합니다')]"
    IMAGE_REQUIRED_MESSAGE_XPATH = "//p[contains(text(), '리뷰 이미지는 필수입니다')]"
    EAT_SAME_MENU_BTN_XPATH = "//*[@id='root']/div[1]/main/section/section/div[3]/div[2]/div[1]/div[2]/button"
    SAME_MENU_REVIEW_TITLE_XPATH = "//span[text()='또 먹은 후기 등록하기']"